name: ContentWarning
version: '0.2-SNAPSHOT'
main: net.masked.contentWarning.ContentWarning
api-version: '26.1'
authors: [Futhark (Forgotten_Devil)]
description: From Marijuana to Shrooms, this adds everything in between
commands:
  contentwarning:
    description: "Main command in the plugin"
    usage: "/contentwarning [items all]"
    aliases: [cw, contwarn]
    permission: permission.contentwarning
    permission-message: "You don't have permission to use this command"